/*
# ECG Attachments Storage Bucket

Creates a private storage bucket `ecg-attachments` for ECG files (images, PDFs, videos).
Files are NOT publicly accessible — they are read via signed URLs generated by the app.
Storage policies allow anon + authenticated to upload/list/delete (single-tenant staff app).
*/

INSERT INTO storage.buckets (id, name, public)
VALUES ('ecg-attachments', 'ecg-attachments', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "anon_upload_ecg" ON storage.objects;
CREATE POLICY "anon_upload_ecg" ON storage.objects
  FOR INSERT TO anon, authenticated
  WITH CHECK (bucket_id = 'ecg-attachments');

DROP POLICY IF EXISTS "anon_read_ecg" ON storage.objects;
CREATE POLICY "anon_read_ecg" ON storage.objects
  FOR SELECT TO anon, authenticated
  USING (bucket_id = 'ecg-attachments');

DROP POLICY IF EXISTS "anon_delete_ecg" ON storage.objects;
CREATE POLICY "anon_delete_ecg" ON storage.objects
  FOR DELETE TO anon, authenticated
  USING (bucket_id = 'ecg-attachments');